### ISSUE TITLE
Includes configuration in jail.local template prevents fail2ban from starting

### ISSUE THREAD

**Issue by emielmolenaar** [archf/fail2ban#1]
The [INCLUDES] section in the jail.local template breaks fail2ban from starting here on Debian Wheezy:

```
[....] Restarting authentication failure monitor: fail2banTraceback (most recent call last):
  File "/usr/bin/fail2ban-client", line 404, in <module>
    if client.start(sys.argv):
  File "/usr/bin/fail2ban-client", line 373, in start
    return self.__processCommand(args)
  File "/usr/bin/fail2ban-client", line 183, in __processCommand
    ret = self.__readConfig()
  File "/usr/bin/fail2ban-client", line 378, in __readConfig
    ret = self.__configurator.getOptions()
  File "/usr/share/fail2ban/client/configurator.py", line 68, in getOptions
    return self.__jails.getOptions(jail)
  File "/usr/share/fail2ban/client/jailsreader.py", line 67, in getOptions
    ret = jail.getOptions()
  File "/usr/share/fail2ban/client/jailreader.py", line 73, in getOptions
    self.__opts = ConfigReader.getOptions(self, self.__name, opts)
  File "/usr/share/fail2ban/client/configreader.py", line 87, in getOptions
    v = self.get(sec, option[1])
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 726, in _interpolate_some
    section, map, depth + 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
    section: [INCLUDES]
    option : action
    key    : port
    rawval : ", protocol="%(protocol)s", chain="%(chain)s"]

 failed!
```

Removing the section "fixes" the error. I can't really figure out _why_ it's blowing up here, anyone got any idea?

**Comment by archf** [comment]
I indeed reproduced the problem with the following setup:

``` shell
vagrant@f2ban-m1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
vagrant@f2ban-m1:~$ cat /etc/fail2ban/
action.d/      filter.d/      jail.local     
fail2ban.conf  jail.conf      
vagrant@f2ban-m1:~$ cat /etc/fail2ban/jail.local 
# file: jail.local
# This configuration file overrides the settings in jail.conf

# The DEFAULT allows a global definition of the options. They can be override
# in each jail afterwards.

[INCLUDES]

#before = paths-distro.conf
before = paths-debian.conf

[DEFAULT]

maxretry = 3
bantime = 600

[sshd]
enabled = true
maxretry = 5

vagrant@f2ban-m1:~$ fail2ban-
fail2ban-client  fail2ban-regex   fail2ban-server  
vagrant@f2ban-m1:~$ fail2ban-client -V
Fail2Ban v0.8.6
```

For the record: 
- debian wheezy uses `Fail2Ban v0.8.6`
- debian jessie  uses `Fail2Ban v0.8.13`
- ubuntu 16.04 uses `Fail2Ban v0.9.3`

I added a Vagrantfile in the tests dir to test it out and what bothers me most is that ansible doesn't seem to trap the error. For instance (wheezy is f2ban-m1):

``` shell
[...snip...]

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [f2ban-m1]
ok: [f2ban-m2]
ok: [f2ban-m3]

TASK [fail2ban : install fail2ban package] *************************************
ok: [f2ban-m1]
ok: [f2ban-m2]
ok: [f2ban-m3]

TASK [fail2ban : template jail2ban jail.local configuration file] **************
ok: [f2ban-m2]
changed: [f2ban-m1]
ok: [f2ban-m3]

TASK [fail2ban : start/stop fail2ban service] **********************************
ok: [f2ban-m2]
ok: [f2ban-m3]
changed: [f2ban-m1]

RUNNING HANDLER [fail2ban : restart_fail2ban] **********************************
changed: [f2ban-m1]

PLAY RECAP *********************************************************************
f2ban-m1                   : ok=5    changed=3    unreachable=0    failed=0   
f2ban-m2                   : ok=4    changed=0    unreachable=0    failed=0   
f2ban-m3                   : ok=4    changed=0    unreachable=0    failed=0
```

My suggestion is to try and see if there is a fail2ban package you can backport.

I don't use this role much lately since i sometimes make use of this project of mine [firetables](https://github.com/archf/firetables) (don't believe everything the readme says yet btw) and this requires me to disable anything `iptables`

**Comment by emielmolenaar** [comment]
Thank you for this information! Great work. And indeed, Ansible for some reason does not trap any error while restarting fail2ban. Should have something to do with some missing exit code or something.

I'll just find a way to install a new version of fail2ban.
